Repository Health-Informatics-UoN/beacon-tools, pull requests merged in 2024-04, with the labels that each got.

#36 Minio service
  app/BeaconBridge/BeaconBridge.csproj
  app/BeaconBridge/Config/MinioOptions.cs
  app/BeaconBridge/Services/MinioStoreService.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
Labels: 🛠️ backlog

#38 Add Missing Constructors in Submission DB Context
  app/BeaconBridge/Data/SubmissionContext.cs
Labels: 🐛 bug

#39 Add FiveSafes.Net from `RquestBridge`
  BeaconBridge.sln
  lib/FiveSafes.Net/BagItArchive.cs
  lib/FiveSafes.Net/Constants/BagItConstants.cs
  lib/FiveSafes.Net/Constants/FiveSafesProfile.cs
  lib/FiveSafes.Net/FiveSafes.Net.csproj
  lib/FiveSafes.Net/FiveSafesBagItBuilder.cs
  lib/FiveSafes.Net/Utilities/ChecksumUtility.cs
  tests/FiveSafes.Net.Tests/FiveSafes.Net.Tests.csproj
  tests/FiveSafes.Net.Tests/GlobalUsings.cs
  tests/FiveSafes.Net.Tests/TestBagItArchive.cs
  tests/FiveSafes.Net.Tests/TestChecksumUtility.cs
  tests/FiveSafes.Net.Tests/TestFiveSafesBagItBuilder.cs
Labels: 🛠️ backlog

#41 Debug/fix openid service
  app/BeaconBridge/BeaconBridge.csproj
  app/BeaconBridge/Services/OpenIdIdentityService.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
Labels: 🐛 bug

#42 Ro crate packaging
  app/BeaconBridge/BeaconBridge.csproj
  app/BeaconBridge/Config/AgreementPolicyOptions.cs
  app/BeaconBridge/Config/AssessActionsOptions.cs
  app/BeaconBridge/Config/CrateAgentOptions.cs
  app/BeaconBridge/Config/CrateOrganizationOptions.cs
  app/BeaconBridge/Config/CrateProjectOptions.cs
  app/BeaconBridge/Config/CratePublishingOptions.cs
  app/BeaconBridge/Config/WorkflowOptions.cs
  app/BeaconBridge/Constants/ActionStatus.cs
  app/BeaconBridge/Services/CrateGenerationService.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
  app/BeaconBridge/Utilities/RoCrateBuilder.cs
Labels: 🛠️ backlog

#46 Add models for TES tasks
  app/BeaconBridge/Models/Submission/Tes/TesCancelTaskResponse.cs
  app/BeaconBridge/Models/Submission/Tes/TesCreateTaskResponse.cs
  app/BeaconBridge/Models/Submission/Tes/TesExecutor.cs
  app/BeaconBridge/Models/Submission/Tes/TesExecutorLog.cs
  app/BeaconBridge/Models/Submission/Tes/TesFileType.cs
  app/BeaconBridge/Models/Submission/Tes/TesInput.cs
  app/BeaconBridge/Models/Submission/Tes/TesListTasksResponse.cs
  app/BeaconBridge/Models/Submission/Tes/TesOutput.cs
  app/BeaconBridge/Models/Submission/Tes/TesOutputFileLog.cs
  app/BeaconBridge/Models/Submission/Tes/TesResources.cs
  app/BeaconBridge/Models/Submission/Tes/TesServiceInfo.cs
  app/BeaconBridge/Models/Submission/Tes/TesState.cs
  app/BeaconBridge/Models/Submission/Tes/TesTask.cs
  app/BeaconBridge/Models/Submission/Tes/TesTaskLog.cs
  app/BeaconBridge/Utilities/NewtonsoftJsonSafeInit.cs
Labels: 🛠️ backlog

#47 Submit filtering terms wf run
  app/BeaconBridge/Config/FilteringTermsUpdateOptions.cs
  app/BeaconBridge/Config/SubmissionOptions.cs
  app/BeaconBridge/Services/Hosted/TriggerFilteringTermsService.cs
  app/BeaconBridge/Services/MinioStoreService.cs
  app/BeaconBridge/Services/TesSubmissionService.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
  tests/BeaconBridge.Tests/BeaconBridge.Tests.csproj
  tests/BeaconBridge.Tests/TestMinioStoreService.cs
Labels: 🛠️ backlog

#51 Set up beacon-omop-worker with basic models,entities and db_manager
  app/beacon-omop-worker/.gitignore
  app/beacon-omop-worker/Dockerfile
  app/beacon-omop-worker/LICENSE
  app/beacon-omop-worker/README.md
  app/beacon-omop-worker/beacon_omop_worker/__about__.py
  app/beacon-omop-worker/beacon_omop_worker/__init__.py
  app/beacon-omop-worker/beacon_omop_worker/beacon_dto/__init__.py
  app/beacon-omop-worker/beacon_omop_worker/beacon_dto/base_dto.py
  app/beacon-omop-worker/beacon_omop_worker/beacon_dto/file.py
  app/beacon-omop-worker/beacon_omop_worker/config.py
  app/beacon-omop-worker/beacon_omop_worker/db_manager.py
  app/beacon-omop-worker/beacon_omop_worker/entities.py
  app/beacon-omop-worker/beacon_omop_worker/query_solvers.py
  app/beacon-omop-worker/pyproject.toml
  app/beacon-omop-worker/scripts/__init__.py
  app/beacon-omop-worker/scripts/worker.py
Labels: 💡 feature request, 🛠️ backlog

#53 Feature/post endpoint filtering terms
  app/BeaconBridge/Controllers/InfoController.cs
  app/BeaconBridge/MappingProfiles/FilteringTermsProfile.cs
  app/BeaconBridge/Models/FilteringTermsRequestBody.cs
Labels: 🛠️ backlog

#52 Cache filter results
  app/BeaconBridge/Config/FilteringTermsUpdateOptions.cs
  app/BeaconBridge/MappingProfiles/FilteringTermProfile.cs
  app/BeaconBridge/Services/FilteringTermsService.cs
  app/BeaconBridge/Services/Hosted/FetchFilteringTermsService.cs
  app/BeaconBridge/Services/MinioStoreService.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
Labels: 🛠️ backlog

#57 use postgres
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
Labels: 🛠️ backlog

#59 Bugfix/reduce crash risk
  app/BeaconBridge/Services/Hosted/FetchFilteringTermsService.cs
  app/BeaconBridge/Services/Hosted/TriggerFilteringTermsService.cs
  app/BeaconBridge/Services/TesSubmissionService.cs
Labels: 🐛 bug

#62 remove automatic migrations
  app/BeaconBridge/Startup/Web/WebEntrypoint.cs
Labels: 🛠️ backlog

#65 Updated FilteringTerms data
  app/BeaconBridge/SampleData/filtering_terms.json
Labels: 🛠️ backlog

#63 Extract filters script
  app/beacon-omop-worker/beacon_omop_worker/beacon_dto/filtering_term.py
  app/beacon-omop-worker/beacon_omop_worker/entities.py
  app/beacon-omop-worker/beacon_omop_worker/query_solvers.py
  app/beacon-omop-worker/pyproject.toml
  app/beacon-omop-worker/scripts/worker.py
Labels: 💡 feature request, 🛠️ backlog

#66 Feature/build and deploy pipelines
  .github/workflows/build.beacon-bridge.yml
  .github/workflows/deploy.beacon-bridge.yml
Labels: 🛠️ backlog

#69 Bugfix/update deployment
  .azure/bicep/hutch-beacon/prod.bicepparam
  .azure/bicep/main.bicep
  .github/workflows/deploy.beacon-bridge.yml
Labels: 🛠️ backlog

#75 Query endpoint
  app/BeaconBridge/Constants/DefaultSchemas.cs
  app/BeaconBridge/Controllers/EntryTypeController.cs
  app/BeaconBridge/Models/BaseMeta.cs
  app/BeaconBridge/Models/EntryTypeResponse.cs
  app/BeaconBridge/Models/Meta.cs
  app/BeaconBridge/Models/RequestSummary.cs
  app/BeaconBridge/Models/ReturnedSchema.cs
  app/BeaconBridge/Startup/Web/ConfigureWebService.cs
Labels: 🛠️ backlog

#77 set static values for datetime params in BaseResponse.cs
  app/BeaconBridge/Models/BaseResponse.cs
Labels: 🛠️ backlog
